site_name: MongoDB Python Developer Path
site_author: Antonio Martinez Fernandez
repo_url: https://github.com/AntonioMrtz/mongodb-python-dev-path
site_description: MongoDB Python Developer Path Documentation
remote_branch: gh-pages

nav:
  - Home: index.md
  - BSON: BSON/BSON.md
  
  - mongosh:
    - Connect: mongosh/Connect.md
    - Insert: mongosh/Insert.md
    - Find: mongosh/Find.md
    - Update: mongosh/Update.md
    - Delete: mongosh/Delete.md
    - Lookup: mongosh/Lookup.md
    - Modifying Query Results: mongosh/Modifying_Query_Results.md
    - Aggregation: mongosh/Aggregation.md
    - Indexes: mongosh/Indexes.md
    - Operators: mongosh/Operators.md
    - Schema validation: mongosh/Schema_Validation.md
    - Bulk Write: mongosh/Bulk_Write.md
    
  - pymongo: 
    - Connection: python/Connection.md 
    - Insert: python/Insert.md
    - Find: python/Find.md
    - Update: python/Update.md
    - Delete: python/Delete.md
    - Aggregation: python/Aggregation.md
    - Transactions: python/Transactions.md
    - Bulk Write: python/Bulk_Write.md

  - Model design:
    - Analysis: Model_Design/Analysis.md
  
theme:
  logo: assets/logo.png
  name: material
  favicon: assets/logo.png
  features:
    - navigation.indexes
  palette:
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences